### ISSUE TITLE
Unable to get this to work

### ISSUE THREAD

**Issue by TsunayoshiSawada** [trgwii/TeMiCross#5]
![image](https://user-images.githubusercontent.com/34431649/106756906-c2b7a280-6655-11eb-8086-caff546994ef.png)
![image](https://user-images.githubusercontent.com/34431649/106756922-c814ed00-6655-11eb-92cb-77d31e33b191.png)

![image](https://user-images.githubusercontent.com/34431649/106757011-e37ff800-6655-11eb-9557-212b45d84d6b.png)
Bot replies but wasnt able to get it to list the users or text to and fro

**Comment by TsunayoshiSawada** [comment]
Another update 
I have closed the cmd window but the server is still running headless, cant seem to find a way to stop it either except a reboot which Im gonna avoid.

**Comment by TsunayoshiSawada** [comment]
Killed all java processes 
Starting again 
Ran tmc botwrap config and rechecked everything and the server is up.
![image](https://user-images.githubusercontent.com/34431649/106758477-8e44e600-6657-11eb-85d4-21e8f4466b7b.png)

Still a little bit stuck. 
![image](https://user-images.githubusercontent.com/34431649/106758596-b2a0c280-6657-11eb-9582-e97fad54a973.png)
After running bot commands the console exists and the server does not 
![image](https://user-images.githubusercontent.com/34431649/106759013-3c509000-6658-11eb-802d-c2b59d46457a.png)
I am still logged in to the running server, its running with no console window
![image](https://user-images.githubusercontent.com/34431649/106759106-58ecc800-6658-11eb-8af8-eb93863d9fae.png)


I noticed its warning for java being outdated, I'll update that as well.

**Comment by trgwii** [comment]
On startup, TeMiCross tries to send "list" in the server console to get the player list, on some non-vanilla servers, they have a different output format for commands, and TeMiCross can't parse the output. You should try putting:
`"type": "spigot"`
Into your botwrap.json / wrapper.json file and restarting TeMiCross.

**Comment by TsunayoshiSawada** [comment]
Thank you for the quick response, I'll test this out and get back to you.

**Comment by TsunayoshiSawada** [comment]
Unable to see any of the two mentioned files. 
Using [paper minecraft](https://papermc.io/downloads)
Directory structure is 
![image](https://user-images.githubusercontent.com/34431649/106762052-740d0700-665b-11eb-9543-1ef3163bd1e5.png)
![image](https://user-images.githubusercontent.com/34431649/106762083-7cfdd880-665b-11eb-9bd0-d4140b6b0d40.png)

I looked around their documentation but wasn't able to find any such config value either. 
I do see [this](https://paper.readthedocs.io/en/latest/server/configuration.html?highlight=spigot#configuration), do we need to switch away from paper to spigot or am i missing something here?

**Comment by trgwii** [comment]
Actually, try: `"servertype": "old-spigot"`

**Comment by RaXorX** [comment]
I just saw this and seems to be what I am experiencing too. And it's not just non-vanilla servers. It happens with vanilla too and probably only on windows.

**Comment by TsunayoshiSawada** [comment]
> I just saw this and seems to be what I am experiencing too. And it's not just non-vanilla servers. It happens with vanilla too and probably only on windows.

Here is what we ended up doing. 
We used discordsrv which is a Minecraft discord plugin, setup a bridge for discord and Minecraft. 
and then setup a matrix bridge (or tedicross would work fine too) bet telegram and discord. 

I now have full control of Minecraft via discord and we can mobile monitor via telegram if we are out of the house. 
It works. 
But Yes, this is not the solution to the problem on this thread, that needs more research.

**Comment by RaXorX** [comment]
> > I just saw this and seems to be what I am experiencing too. And it's not just non-vanilla servers. It happens with vanilla too and probably only on windows.
> 
> Here is what we ended up doing.
> We used discordsrv which is a Minecraft discord plugin, setup a bridge for discord and Minecraft.
> and then setup a matrix bridge (or tedicross would work fine too) bet telegram and discord.
> 
> I now have full control of Minecraft via discord and we can mobile monitor via telegram if we are out of the house.
> It works.
> But Yes, this is not the solution to the problem on this thread, that needs more research.

In my case I might have pinpointed the issue out with help from @YukariChiba. He's the one who mainly diagnosed it out but for me, on a fabric server and normally on vanilla too the output for players joining in is different than what you have in PaperMC (which goes as UUID of player playername is). Which is why it doesn't sees any players online and hence, since there's no one online doesn't send the messages from telegram to server. I'll try changing the detection message and test it out. Will post results soon. 

EDIT: Changed "UUID of player (?<user>" + username + ") is (?<uuid>.+)$"; to "(?<user>" + username + ") joined the game"; in join.js for the default parser. That solved it for me. 
I'll be closing [this](https://github.com/trgwii/TeMiCross/issues/7) though

**Comment by trgwii** [comment]
This has been one of the major problems with this project over the years, Vanilla and other servers all seem to act slightly different in how they display joins, and it also depends on online-mode / offline-mode. If you find some permanent solution that works well across different server versions feel free to make a PR.
